apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-api
  namespace: sleep-platform
imagePullSecrets:
  - name: acr-pull-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-service
  namespace: sleep-platform
imagePullSecrets:
  - name: acr-pull-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: feature-service
  namespace: sleep-platform
imagePullSecrets:
  - name: acr-pull-secret
