apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sleep-platform
resources:
  - ../../base
  - external-egress.yaml
  - validation-redis.yaml
  - validation-clickhouse.yaml
  - validation-data-network-policy.yaml
patches:
  - path: backend-loadbalancer-patch.yaml
  - path: validation-capacity-patch.yaml
  - path: acr-pull-secret-patch.yaml
images:
  - name: registry.example.com/sleep/backend-api
    newName: registry-vpc.cn-hangzhou.aliyuncs.com/REPLACE_WITH_ACR_NAMESPACE/backend-api
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
  - name: registry.example.com/sleep/agent-service
    newName: registry-vpc.cn-hangzhou.aliyuncs.com/REPLACE_WITH_ACR_NAMESPACE/agent-service
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
  - name: registry.example.com/sleep/feature-service
    newName: registry-vpc.cn-hangzhou.aliyuncs.com/REPLACE_WITH_ACR_NAMESPACE/feature-service
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
